/* Code automatically generated by micro-controller GUI programming */


/* initialisation of variables according to pin configuration*/

int led1 = D1;

/* setup() function initialising the pin configuration*/

void setup(){
	pinMode(led1,OUTPUT);
}

/* Switch case implementing the different states*/

typedef enum{
	led_on,
	led_off,
states;

states s = led_off;

/* The loop function runs over and over again forever */
void loop(){
	switch(s){
		case led_on:
			digitalWrite(led1,HIGH);
			s = led_off;
		case led_off:
			digitalWrite(led1,LOW);
			s = led_on;
		default:
			printf("Default case not admissible");
}