/* Code automatically generated by micro-controller GUI programming */


/* initialisation of variables according to pin configuration*/

int led = 13;

/* setup() function initialising the pin configuration */

void setup() {
	pinMode(led,OUTPUT);
}

/* Switch case implementing the different states*/

typedef enum {
	led_on,
} states;

states s = led_on;

/* The loop function runs over and over again forever */
void loop() {
	switch(s){
		case led_on:
			digitalWrite(led,HIGH);
			break;
		default:
			printf("Default case not admissible");
	}
}